

Builddemo: Builddemo.o add.o sub.o	
	gcc -o Builddemo Builddemo.o add.o sub.o


Builddemo.o : Builddemo.c
	gcc -c -o Builddemo.o Builddemo.c

add.o : add.c
	gcc -c -o add.o add.c


sub.o : sub.c
	gcc -c -o sub.o sub.c